const knowledgeArticles = [
  {
    title: 'What is Phishing?',
    category: 'Phishing',
    content: 'Phishing is a type of social engineering attack where attackers disguise themselves as trustworthy entities to trick people into revealing sensitive information such as passwords, credit card numbers, or personal data. These attacks typically come through email, text messages, or fake websites that look legitimate. Phishing is one of the most common cyber threats and can affect anyone, from individuals to large organizations.',
    prevention: 'Always verify the sender\'s email address before clicking links. Look for misspellings in URLs. Never provide sensitive information through email. Use email filters and anti-phishing tools. When in doubt, contact the organization directly through their official website.',
    recommendedActions: [
      'Enable email spam filters',
      'Verify sender email addresses',
      'Hover over links before clicking',
      'Report suspicious emails',
      'Use multi-factor authentication',
    ],
    tags: ['phishing', 'email', 'social engineering', 'scam'],
  },
  {
    title: 'What is Malware?',
    category: 'Malware',
    content: 'Malware (malicious software) is any software intentionally designed to cause damage to a computer, server, client, or computer network. Types include viruses, worms, trojans, ransomware, spyware, adware, and more. Malware can steal data, encrypt files for ransom, spy on activities, or damage systems. It often spreads through email attachments, malicious downloads, or compromised websites.',
    prevention: 'Keep your operating system and software updated. Use reputable antivirus software. Don\'t download files from untrusted sources. Be cautious with email attachments. Use a firewall and keep it enabled.',
    recommendedActions: [
      'Install and update antivirus software',
      'Keep OS and apps updated',
      'Avoid downloading from untrusted sources',
      'Scan files before opening',
      'Use a firewall',
    ],
    tags: ['malware', 'virus', 'security', 'protection'],
  },
  {
    title: 'What is Ransomware?',
    category: 'Malware',
    content: 'Ransomware is a type of malware that encrypts a victim\'s files or locks them out of their system. The attacker then demands a ransom payment (usually in cryptocurrency) to restore access. Ransomware attacks can target individuals, businesses, hospitals, and government agencies. Even after paying the ransom, there is no guarantee that access will be restored.',
    prevention: 'Regularly back up your data to an offline or cloud storage. Keep software updated. Don\'t open suspicious email attachments. Use strong anti-malware protection. Implement the principle of least privilege for system access.',
    recommendedActions: [
      'Maintain regular offline backups',
      'Never pay the ransom',
      'Report to law enforcement',
      'Disconnect infected systems from the network',
      'Restore from clean backups',
    ],
    tags: ['ransomware', 'malware', 'encryption', 'backup'],
  },
  {
    title: 'What is Spyware?',
    category: 'Malware',
    content: 'Spyware is malicious software that secretly monitors and collects information about a user\'s activities without their knowledge. It can capture keystrokes (keylogger), take screenshots, track browsing habits, access cameras/microphones, and steal sensitive data. Spyware often comes bundled with free software, through malicious ads, or via phishing attacks.',
    prevention: 'Download software only from trusted sources. Read permissions before installing apps. Use anti-spyware tools. Keep your system updated. Be cautious with free software and browser extensions.',
    recommendedActions: [
      'Run anti-spyware scans regularly',
      'Review app permissions',
      'Remove suspicious applications',
      'Monitor system performance for unusual activity',
      'Use privacy-focused browsers',
    ],
    tags: ['spyware', 'malware', 'privacy', 'monitoring'],
  },
  {
    title: 'What is a Trojan Horse?',
    category: 'Malware',
    content: 'A Trojan horse (or simply Trojan) is a type of malware that disguises itself as legitimate software. Unlike viruses, Trojans don\'t replicate themselves. Instead, they trick users into installing them, then create backdoors for attackers, steal data, or install additional malware. Common types include banking Trojans, remote access Trojans (RATs), and downloader Trojans.',
    prevention: 'Only download software from official sources. Verify software integrity with checksums when available. Keep antivirus software updated. Be wary of free versions of paid software. Don\'t click on suspicious pop-ups.',
    recommendedActions: [
      'Download from official sources only',
      'Use antivirus with real-time protection',
      'Verify software before installing',
      'Monitor outgoing network traffic',
      'Remove suspicious programs immediately',
    ],
    tags: ['trojan', 'malware', 'backdoor', 'security'],
  },
  {
    title: 'What is a Computer Worm?',
    category: 'Malware',
    content: 'A computer worm is a type of malware that replicates itself and spreads across networks without human interaction. Unlike viruses, worms don\'t need to attach to existing programs. They exploit vulnerabilities in operating systems or applications to spread rapidly, potentially affecting thousands of computers. Worms can consume bandwidth, delete files, install backdoors, or carry other malicious payloads.',
    prevention: 'Keep your operating system and software updated with the latest patches. Use a firewall to block unauthorized access. Install and update antivirus software. Segment your network to limit spread. Disable unnecessary services.',
    recommendedActions: [
      'Apply security patches promptly',
      'Use network segmentation',
      'Enable firewall protection',
      'Monitor network traffic for anomalies',
      'Isolate infected systems immediately',
    ],
    tags: ['worm', 'malware', 'network', 'vulnerability'],
  },
  {
    title: 'What is Social Engineering?',
    category: 'Social Engineering',
    content: 'Social engineering is the art of manipulating people into giving up confidential information or performing actions that compromise security. Instead of hacking systems directly, attackers exploit human psychology — trust, fear, urgency, or curiosity. Common techniques include phishing, pretexting (creating a fabricated scenario), baiting (leaving infected USB drives), and tailgating (following someone into a restricted area).',
    prevention: 'Be skeptical of unsolicited requests for information. Verify identities before sharing sensitive data. Don\'t act on urgency or pressure. Educate yourself and your team about social engineering tactics. Implement security awareness training.',
    recommendedActions: [
      'Question unexpected requests',
      'Verify identities through official channels',
      'Never share passwords over phone or email',
      'Report suspicious contacts to security team',
      'Take security awareness training regularly',
    ],
    tags: ['social engineering', 'manipulation', 'security awareness', 'human factor'],
  },
  {
    title: 'What is Eavesdropping in Cybersecurity?',
    category: 'Privacy',
    content: 'Eavesdropping (or sniffing) in cybersecurity refers to the unauthorized interception of network communications. Attackers can capture data transmitted over unsecured networks, including passwords, emails, and financial information. This is especially common on public Wi-Fi networks. Techniques include packet sniffing, man-in-the-middle attacks, and session hijacking.',
    prevention: 'Use encrypted connections (HTTPS, VPN). Avoid transmitting sensitive data on public Wi-Fi. Use WPA3 encryption on your Wi-Fi network. Enable end-to-end encryption for messaging. Verify website certificates.',
    recommendedActions: [
      'Use a VPN on public networks',
      'Check for HTTPS before entering data',
      'Avoid public Wi-Fi for sensitive transactions',
      'Use encrypted messaging apps',
      'Enable WPA3 on your home Wi-Fi',
    ],
    tags: ['eavesdropping', 'privacy', 'network', 'encryption', 'sniffing'],
  },
  {
    title: 'How to Create a Strong Password',
    category: 'Password Security',
    content: 'A strong password is your first line of defense against unauthorized access. Strong passwords should be at least 12 characters long and include a mix of uppercase letters, lowercase letters, numbers, and special characters. Avoid using personal information, common words, or sequential characters. Each account should have a unique password. Consider using a password manager to generate and store complex passwords securely.',
    prevention: 'Use a password manager. Enable multi-factor authentication. Don\'t reuse passwords across accounts. Change passwords periodically, especially after a breach. Never share passwords.',
    recommendedActions: [
      'Use a password manager (e.g., Bitwarden, 1Password)',
      'Create passwords with 12+ characters',
      'Use a mix of letters, numbers, and symbols',
      'Never reuse passwords across accounts',
      'Enable MFA on all important accounts',
    ],
    tags: ['password', 'security', 'authentication', 'best practices'],
  },
  {
    title: 'Why Multi-Factor Authentication (MFA) is Important',
    category: 'Account Security',
    content: 'Multi-Factor Authentication (MFA) adds an extra layer of security beyond just a password. It requires two or more verification methods: something you know (password), something you have (phone, security key), or something you are (fingerprint, face ID). Even if an attacker steals your password, they cannot access your account without the second factor. MFA can prevent up to 99.9% of account compromise attacks.',
    prevention: 'Enable MFA on all accounts that support it. Prefer authenticator apps (like Google Authenticator or Authy) over SMS-based MFA. Keep backup codes in a safe place. Use hardware security keys for highest security.',
    recommendedActions: [
      'Enable MFA on email, banking, and social media',
      'Use authenticator apps instead of SMS',
      'Store backup codes securely',
      'Consider hardware security keys',
      'Review MFA settings regularly',
    ],
    tags: ['mfa', 'two-factor', 'authentication', 'account security'],
  },
  {
    title: 'Safe Public Wi-Fi Practices',
    category: 'Safe Browsing',
    content: 'Public Wi-Fi networks (in cafes, airports, hotels) are convenient but potentially dangerous. Attackers can set up rogue hotspots that look legitimate, or intercept data on unsecured networks. Activities like online banking, shopping, or accessing sensitive accounts on public Wi-Fi put your data at risk. Man-in-the-middle attacks are particularly common on these networks.',
    prevention: 'Always use a VPN when connecting to public Wi-Fi. Avoid accessing sensitive accounts on public networks. Turn off auto-connect to Wi-Fi. Verify the network name with the establishment. Use your mobile data for sensitive transactions.',
    recommendedActions: [
      'Use a reputable VPN service',
      'Turn off Wi-Fi auto-connect',
      'Avoid online banking on public Wi-Fi',
      'Verify network names with staff',
      'Use mobile data for sensitive tasks',
    ],
    tags: ['wifi', 'public network', 'vpn', 'safe browsing'],
  },
  {
    title: 'Safe Browsing Practices',
    category: 'Safe Browsing',
    content: 'Safe browsing means being careful about what you click, download, and share online. Malicious websites can install malware, steal credentials, or trick you into revealing personal information. Browser extensions, pop-ups, and redirects are common attack vectors. Keeping your browser updated and using security extensions can significantly reduce your risk.',
    prevention: 'Keep your browser updated. Use HTTPS-only mode. Install a reputable ad blocker. Don\'t click on suspicious pop-ups. Verify URLs before entering credentials. Use browser security extensions.',
    recommendedActions: [
      'Keep browser updated to latest version',
      'Enable HTTPS-only mode',
      'Use an ad blocker',
      'Check URLs carefully before clicking',
      'Avoid downloading from unknown websites',
    ],
    tags: ['browsing', 'web safety', 'https', 'browser security'],
  },
  {
    title: 'Account Security Best Practices',
    category: 'Account Security',
    content: 'Securing your online accounts is crucial in today\'s digital world. Compromised accounts can lead to identity theft, financial loss, and privacy violations. Key practices include using unique strong passwords, enabling MFA, reviewing account activity regularly, and being aware of data breaches that may have exposed your credentials. Many services offer security checkups and activity logs that can help you stay secure.',
    prevention: 'Use unique passwords for each account. Enable MFA. Review login activity regularly. Set up account recovery options. Be cautious of password reset emails you didn\'t request.',
    recommendedActions: [
      'Check if your email is in data breaches (haveibeenpwned.com)',
      'Enable login notifications',
      'Review connected apps and permissions',
      'Set up account recovery options',
      'Use a password manager for unique passwords',
    ],
    tags: ['account', 'security', 'identity', 'protection'],
  },
  {
    title: 'Data Privacy Fundamentals',
    category: 'Privacy',
    content: 'Data privacy is about controlling how your personal information is collected, used, and shared. In the digital age, companies collect vast amounts of data including browsing habits, location, preferences, and personal details. Understanding privacy settings, data collection practices, and your rights is essential. Regulations like GDPR and CCPA give users more control over their data.',
    prevention: 'Review privacy settings on all accounts. Limit data sharing with apps and services. Use privacy-focused tools and browsers. Read privacy policies before signing up. Regularly delete unused accounts.',
    recommendedActions: [
      'Review social media privacy settings',
      'Limit app permissions',
      'Use privacy-focused search engines',
      'Delete unused online accounts',
      'Opt out of data collection when possible',
    ],
    tags: ['privacy', 'data protection', 'gdpr', 'personal information'],
  },
  {
    title: 'How to Recognize Phishing Emails',
    category: 'Phishing',
    content: 'Phishing emails are designed to look like they come from legitimate sources such as banks, social media, or online services. Common signs include: generic greetings ("Dear Customer"), urgent language ("Your account will be suspended"), misspelled sender domains (g00gle.com instead of google.com), suspicious attachments, and requests for personal information. Modern phishing can be very sophisticated, making it crucial to stay vigilant.',
    prevention: 'Check the sender\'s actual email address (not just the display name). Look for grammar and spelling errors. Don\'t click links — hover to see the actual URL. Never download unexpected attachments. When in doubt, go directly to the official website.',
    recommendedActions: [
      'Hover over links to check URLs',
      'Verify sender email addresses carefully',
      'Don\'t download unexpected attachments',
      'Report phishing emails to your email provider',
      'Contact the company directly if unsure',
    ],
    tags: ['phishing', 'email', 'recognition', 'scam'],
  },
  {
    title: 'What to Do if Your Account is Hacked',
    category: 'Account Security',
    content: 'If you suspect your account has been hacked, act quickly. Signs include: unexpected password changes, unfamiliar login locations, messages you didn\'t send, or purchases you didn\'t make. Quick action can minimize damage and help you regain control of your account. Most major services have account recovery processes designed to help in these situations.',
    prevention: 'Enable MFA to prevent future hacks. Use unique passwords. Monitor account activity. Set up login alerts. Keep recovery options updated.',
    recommendedActions: [
      'Change your password immediately',
      'Enable or reset MFA',
      'Check for unauthorized changes to settings',
      'Review and revoke unknown sessions',
      'Contact the service\'s support team',
      'Check connected accounts for compromise',
      'Monitor for identity theft',
    ],
    tags: ['hacked', 'account recovery', 'security breach', 'incident response'],
  },
  {
    title: 'Understanding Software Updates and Patches',
    category: 'Safe Browsing',
    content: 'Software updates and security patches fix vulnerabilities that attackers can exploit. Outdated software is one of the most common ways hackers gain access to systems. Updates address security flaws, fix bugs, and sometimes add new features. Both operating systems and applications need to be kept current. Many major cyberattacks have exploited known vulnerabilities that had patches available.',
    prevention: 'Enable automatic updates where possible. Regularly check for updates on all devices. Update browsers, plugins, and extensions. Don\'t ignore update notifications. Use supported software versions.',
    recommendedActions: [
      'Enable automatic OS updates',
      'Update all applications regularly',
      'Replace software that no longer receives updates',
      'Check for firmware updates on routers and IoT devices',
      'Use a vulnerability scanner for your systems',
    ],
    tags: ['updates', 'patches', 'vulnerability', 'software security'],
  },
  {
    title: 'Secure Your Home Network',
    category: 'Privacy',
    content: 'Your home network is the gateway to all your connected devices. An unsecured home network can allow attackers to intercept your data, access your devices, or use your network for malicious activities. Key aspects include securing your router, using strong encryption, managing connected devices, and monitoring for unauthorized access.',
    prevention: 'Change default router credentials. Use WPA3 encryption. Create a guest network for visitors. Disable WPS. Keep router firmware updated. Use a strong Wi-Fi password.',
    recommendedActions: [
      'Change default router admin password',
      'Enable WPA3 or WPA2 encryption',
      'Update router firmware regularly',
      'Create a separate guest network',
      'Monitor connected devices regularly',
    ],
    tags: ['home network', 'router', 'wifi security', 'iot'],
  },
];

module.exports = knowledgeArticles;
